"""
POST /vectorize — Generate a .mbtiles vector tile package from a spatial file.

Uses tippecanoe (v2+) to produce Mapbox Vector Tiles in MBTiles format.
Customers host the output themselves — we generate and hand off, no storage responsibility.

Inputs:
  file         — any supported spatial format (GeoJSON, Shapefile, GPKG, KML)
  layer_name   — name of the vector layer inside the tiles (default: "data")
  min_zoom     — minimum zoom level, 0–22 (default: 0)
  max_zoom     — maximum zoom level, 0–22 (default: 14)
  simplify     — auto-simplify at low zooms (default: True)
  name         — human-readable tileset name (embedded in mbtiles metadata)
  description  — tileset description (embedded in mbtiles metadata)

Output: .mbtiles file (SQLite container, compatible with Mapbox GL JS, MapLibre, GDAL, etc.)

Hosting the output:
  - Cloudflare R2 + workers-tile-server
  - AWS S3 + Lambda
  - self-hosted: mbview, martin, tileserver-gl
  - Protomaps (pmtiles format conversion)
"""

import os
import shutil
import subprocess
import tempfile
from typing import Optional

import geopandas as gpd

from app.operations.convert import _unpack_upload, detect_format, DRIVER_MAP, WRITE_FORMATS


def run_vectorize(
    file_bytes: bytes,
    filename: str,
    layer_name: str,
    min_zoom: int,
    max_zoom: int,
    simplify: bool,
    tileset_name: str,
    description: str,
) -> tuple[bytes, str, dict]:
    """
    Generate a .mbtiles vector tile package.
    Returns (mbtiles_bytes, output_filename, stats).
    Raises ValueError on bad inputs.
    Raises RuntimeError if tippecanoe fails.
    """
    # Sanitize user-controlled strings passed to subprocess to prevent command injection
    import re
    if not re.match(r'^[a-zA-Z0-9_\-]{1,64}$', layer_name):
        raise ValueError("layer_name must be 1-64 alphanumeric characters, hyphens, or underscores")
    if tileset_name and not re.match(r'^[a-zA-Z0-9 _\-]{1,128}$', tileset_name):
        raise ValueError("tileset_name must be 1-128 alphanumeric characters, spaces, hyphens, or underscores")
    if description and len(description) > 500:
        raise ValueError("description must be 500 characters or fewer")

    if min_zoom < 0 or min_zoom > 22:
        raise ValueError("min_zoom must be between 0 and 22")
    if max_zoom < 0 or max_zoom > 22:
        raise ValueError("max_zoom must be between 0 and 22")
    if min_zoom > max_zoom:
        raise ValueError("min_zoom must be <= max_zoom")
    if max_zoom > 16:
        raise ValueError(
            "max_zoom > 16 is rarely useful and can produce very large files. "
            "Use max_zoom <= 16."
        )

    # Check tippecanoe is available
    tippecanoe_path = shutil.which("tippecanoe")
    # LaunchAgents have minimal PATH — check common Homebrew locations
    if not tippecanoe_path:
        for candidate in ["/opt/homebrew/bin/tippecanoe", "/usr/local/bin/tippecanoe"]:
            if os.path.isfile(candidate):
                tippecanoe_path = candidate
                break
    if not tippecanoe_path:
        raise RuntimeError(
            "tippecanoe is not installed or not in PATH. "
            "Install with: brew install tippecanoe"
        )

    tmpdir = tempfile.mkdtemp(prefix="meridian_tiles_")
    try:
        # Step 1: Unpack and read the input file
        src_path = _unpack_upload(file_bytes, filename, tmpdir)
        gdf = gpd.read_file(src_path)

        if gdf.empty:
            raise ValueError("Input file contains no features.")

        feature_count = len(gdf)
        geom_types = gdf.geometry.geom_type.dropna().unique().tolist()

        # Step 2: Ensure we have WGS84 (tippecanoe requires lat/lon)
        if gdf.crs is None:
            # Assume WGS84 if no CRS
            gdf = gdf.set_crs(epsg=4326)
        elif gdf.crs.to_epsg() != 4326:
            gdf = gdf.to_crs(epsg=4326)

        # Step 3: Write to GeoJSON (tippecanoe's native input)
        geojson_path = os.path.join(tmpdir, "input.geojson")
        gdf.to_file(geojson_path, driver="GeoJSON")

        # Step 4: Build tippecanoe command
        out_path = os.path.join(tmpdir, "output.mbtiles")
        cmd = [
            tippecanoe_path,
            "--output", out_path,
            "--layer", layer_name,
            "--minimum-zoom", str(min_zoom),
            "--maximum-zoom", str(max_zoom),
            "--name", tileset_name or layer_name,
            "--description", description or f"Generated by Node API — nodeapi.ai",
            "--force",          # overwrite if exists
            "--quiet",          # suppress progress output
        ]

        if simplify:
            cmd.append("--drop-densest-as-needed")  # auto-thin at low zooms
            cmd.append("--extend-zooms-if-still-dropping")

        cmd.append(geojson_path)

        # Step 5: Run tippecanoe
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=300,  # 5 minute timeout
        )

        if result.returncode != 0:
            err = result.stderr.strip() or result.stdout.strip()
            raise RuntimeError(f"tippecanoe failed: {err}")

        if not os.path.exists(out_path):
            raise RuntimeError("tippecanoe completed but output file was not created.")

        # Step 6: Read output
        with open(out_path, "rb") as f:
            mbtiles_bytes = f.read()

        # Derive a clean output filename
        stem = os.path.splitext(filename)[0]
        out_filename = f"{stem}_z{min_zoom}-{max_zoom}.mbtiles"

        stats = {
            "input_features": feature_count,
            "geometry_types": geom_types,
            "min_zoom": min_zoom,
            "max_zoom": max_zoom,
            "layer_name": layer_name,
            "size_bytes": len(mbtiles_bytes),
            "tippecanoe_version": "2.79.0",
        }

        return mbtiles_bytes, out_filename, stats

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
